### ISSUE TITLE
Publish to npm w/ repository change

### ISSUE THREAD

**Issue by Lykathia** [unshiftio/requires-port#1]
The current package on npm has a dead link due a typo that was fixed in 3dd93cfd7e24df5cb643488d804a4455597c0d17. Could this package be published as 0.0.1 to fix this link?

Trying to import into WebJars, but the validation checks are failing due to the dead link.

**Comment by 3rd-Eden** [comment]
Published a 0.0.1

**Comment by Lykathia** [comment]
Many Thanks!
